spring:
  application:
    name: mtls-client
  ssl:
    bundle:
      jks:
        client:
          reload-on-update: true
          key:
            #alias: myuser
            password: changeit
          keystore:
            location: classpath:client.p12
            password: changeit
            type: PKCS12
          truststore:
            location: classpath:server-trust.p12
            password: changeit
            type: PKCS12
server:
  port: 8080
logging:
  level:
    org.springframework.web.client: trace
    org.apache.hc.client5: debug
    web: debug
